<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ServiceDemo"
     targetNamespace="http://xmlns.oracle.com/SOAVasplatform/ProjectDemo/ServiceDemo"
     xmlns:tns="http://xmlns.oracle.com/SOAVasplatform/ProjectDemo/ServiceDemo"
     xmlns:inp1="http://vasplatform.mobifone.com"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://vasplatform.mobifone.com" schemaLocation="../Schemas/ProjectNameSchema.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:Request"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="response" element="inp1:Response"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
